### ISSUE TITLE
Add Filter to disable CSS

### ISSUE THREAD

**Issue by cjkoepke** [studiopress/simple-social-icons#56]
On a client's site of mine, when editing the colors for the plugin, the default CSS is overriding the custom CSS in the `head`.

CSS Outputted:

```css
/* Custom CSS */
.simple-social-icons ul li a,
.simple-social-icons ul li a:hover,
.simple-social-icons ul li a:focus {
    background-color: #ffffff !important;
    border-radius: 60px;
    color: #000000 !important;
    border: 0px #ffffff solid !important;
    font-size: 30px;
    padding: 15px;
}
/* Theme Defaults CSS */
.simple-social-icons ul li a:hover,
.simple-social-icons ul li a:focus {
    background-color: #f04848 !important;
    border-color: #ffffff !important;
    color: #ffffff !important;
}
.simple-social-icons ul li a:focus {
    outline: 1px dotted #f04848 !important;
}
```

I'm not sure if this is a theme issue (Brunch is over-specific), or a plugin issue — I'm guess the former but wanted to make sure. We are also hosting the site on Synthesis if more information is needed.
