### ISSUE TITLE
Invalid css output on transparent background

### ISSUE THREAD

**Issue by NormanHoehne** [studiopress/simple-social-icons#93]
If one is using icons with a transparent background, the inline CSS output for the icons hover state will be like this:
`#simple-social-icons-3 ul li a,#simple-social-icons-3 ul li a:hover{background-color:;border-radius:36px;color:#fff;border:0 #fff solid;font-size:18px;padding:9px}#simple-social-icons-3 ul li a:hover{background-color:;border-color:#fff;color:#f60}`

which contains invalid empty background-color declarations.

Tested Version: Simple Social Icons 3.0.0

**Comment by nickcernis** [comment]
@NormanHoehne I can't reproduce this so far. Is this an existing widget or a new one?

I see this inline markup when setting a background color as empty (pretty-printed for clarity):

```CSS
#simple-social-icons-2 ul li a,
#simple-social-icons-2 ul li a:hover,
#simple-social-icons-2 ul li a:focus {
    background-color: transparent !important;
    border-radius: 3px;
    color: #1e73be !important;
    border: 0px #ffffff solid !important;
    font-size: 20px;
    padding: 10px;
}

#simple-social-icons-2 ul li a:hover,
#simple-social-icons-2 ul li a:focus {
    background-color: #eeee22 !important;
    border-color: #ffffff !important;
    color: #ffffff !important;
}

#simple-social-icons-2 ul li a:focus {
    outline: 1px dotted #eeee22 !important;
}

#simple-social-icons-3 ul li a,
#simple-social-icons-3 ul li a:hover,
#simple-social-icons-3 ul li a:focus {
    background-color: #f5f5f5 !important;
    border-radius: 3px;
    color: #dd9933 !important;
    border: 0px #ffffff solid !important;
    font-size: 20px;
    padding: 10px;
}

#simple-social-icons-3 ul li a:hover,
#simple-social-icons-3 ul li a:focus {
    background-color: #333333 !important;
    border-color: #ffffff !important;
    color: #ffffff !important;
}

#simple-social-icons-3 ul li a:focus {
    outline: 1px dotted #333333 !important;
}
```

The background value appears to be correctly set as empty here: https://github.com/studiopress/simple-social-icons/blob/a9105323026d27b249b780ede7f79e4ca0c85da5/simple-social-icons.php#L403

Which outputs transparent here: https://github.com/studiopress/simple-social-icons/blob/a9105323026d27b249b780ede7f79e4ca0c85da5/simple-social-icons.php#L514
